# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-30 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('post_office.email',),
        ),
    ]
