# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0002_auto_20160913_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_relations', to='edw.Entity', verbose_name='From Entity')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.Term', verbose_name='Term')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backward_relations', to='edw.Entity', verbose_name='To Entity')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Entity Relation',
                'verbose_name_plural': 'Entity Relations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entityrelation',
            unique_together=set([('from_entity', 'to_entity', 'term')]),
        ),
    ]
