# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0003_auto_20160913_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.Entity')),
                ('geoposition', geoposition.fields.GeopositionField(max_length=42, verbose_name='Geoposition')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
            bases=('edw.entity',),
        ),
    ]
