# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0004_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.Entity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edw.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('edw.entity',),
        ),
    ]
