# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('edw', '0007_entityimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityimage',
            options={'verbose_name': 'Entity Image', 'verbose_name_plural': 'Entity Images'},
        ),
        migrations.AddField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(through='edw.EntityImage', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edw.Entity', verbose_name='Entity'),
        ),
    ]
