# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0008_auto_20160913_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityimage',
            options={'ordering': ('order',), 'verbose_name': 'Entity Image', 'verbose_name_plural': 'Entity Images'},
        ),
    ]
