# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 15:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0009_auto_20160913_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='slug',
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Image'),
        ),
    ]
