# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0010_auto_20160915_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
