# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 19:12
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0013_entity_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='state',
        ),
        migrations.AddField(
            model_name='particularproblem',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, verbose_name='State'),
        ),
    ]
