# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 15:01
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0016_remove_particularproblem_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='particularproblem',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True, verbose_name='State'),
        ),
    ]
