# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0020_particularproblem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='particularproblem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='edw.Customer', verbose_name='Customer'),
            preserve_default=False,
        ),
    ]
