# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0021_particularproblem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='particularproblem',
            name='stored_request',
            field=jsonfield.fields.JSONField(default={}, help_text='Parts of the Request objects on the moment of submit.'),
        ),
        migrations.AlterField(
            model_name='particularproblem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='edw.Customer', verbose_name='Customer'),
        ),
    ]
