# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0022_auto_20160922_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationattachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
    ]
