# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0023_auto_20160922_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
