# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0010_auto_20160820_0052'),
        ('edw', '0024_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('post_office.email',),
        ),
    ]
