# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0026_auto_20160922_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particularproblem',
            name='customer',
        ),
    ]
