# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 14:14
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0027_remove_particularproblem_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePerson',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.Entity')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
            bases=('edw.entity',),
        ),
        migrations.RemoveField(
            model_name='person',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='entity_ptr',
        ),
        migrations.AddField(
            model_name='entity',
            name='related_data_marts',
            field=models.ManyToManyField(blank=True, related_name='_entity_related_data_marts_+', to='edw.DataMart', verbose_name='Related data marts'),
        ),
        migrations.AddField(
            model_name='entity',
            name='relations',
            field=models.ManyToManyField(through='edw.EntityRelation', to='edw.Entity'),
        ),
        migrations.AlterField(
            model_name='datamart',
            name='system_flags',
            field=bitfield.models.BitField([('delete_restriction', 'Delete restriction'), ('change_parent_restriction', 'Change parent restriction'), ('change_slug_restriction', 'Change slug restriction'), ('has_child_restriction', 'Has child restriction'), ('change_terms_restriction', 'Change terms restriction')], default=None, null=True, verbose_name='system flags'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='PrivatePerson',
            fields=[
                ('baseperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.BasePerson')),
            ],
            options={
                'verbose_name': 'Private person',
                'verbose_name_plural': 'Private persons',
            },
            bases=('edw.baseperson',),
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('baseperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.BasePerson')),
                ('post', models.CharField(blank=True, help_text='Responsible person post', max_length=255, null=True, verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Responsible person',
                'verbose_name_plural': 'Responsible persons',
            },
            bases=('edw.baseperson',),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='baseperson',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edw.Customer', verbose_name='Customer'),
        ),
    ]
