# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0028_auto_20161007_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRelatedDataMart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.DataMart', verbose_name='Data mart')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Related data mart',
                'verbose_name_plural': 'Entity related data marts',
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='related_data_marts',
            field=models.ManyToManyField(blank=True, related_name='_entity_related_data_marts_+', through='edw.EntityRelatedDataMart', to='edw.DataMart', verbose_name='Related data marts'),
        ),
        migrations.AddField(
            model_name='entityrelateddatamart',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.Entity', verbose_name='Entity'),
        ),
    ]
