# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0030_auto_20161011_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMartRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('b', 'Bidirectional'), ('f', 'Forward'), ('r', 'Reverse')], default='b', help_text='Defines the direction of relation on which selection is carried out', max_length=1, verbose_name='Relation direction')),
                ('data_mart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='edw.DataMart', verbose_name='Data mart')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.Term', verbose_name='Term')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Data mart relation',
                'verbose_name_plural': 'Data mart relations',
            },
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='relations',
            new_name='_relations',
        ),
        migrations.AlterField(
            model_name='additionalentitycharacteristicormark',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.Entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='additionalentitycharacteristicormark',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.Term', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='datamart',
            name='_relations',
            field=models.ManyToManyField(through='edw.DataMartRelation', to='edw.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='datamartrelation',
            unique_together=set([('data_mart', 'term')]),
        ),
    ]
