# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0031_auto_20161013_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseperson',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
