# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0032_baseperson_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamart',
            name='ordering',
            field=models.CharField(choices=[('-created_at', 'Created at: new first')], default='-created_at', help_text='Default data mart entities ordering mode.', max_length=50, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='datamart',
            name='slug',
            field=models.SlugField(help_text='Used for URLs, auto-generated from name if blank.', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.SlugField(help_text='Used for URLs, auto-generated from name if blank.', verbose_name='Slug'),
        ),
    ]
