# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0033_auto_20161102_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamart',
            name='ordering',
            field=models.CharField(default='-created_at', help_text='Default data mart entities ordering mode.', max_length=50, verbose_name='Ordering'),
        ),
    ]
