# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0034_auto_20161107_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='order',
        ),
    ]
