# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0036_place_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Postcode'),
        ),
    ]
