# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0037_auto_20161110_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.AddField(
            model_name='baseperson',
            name='name',
            field=models.CharField(default='Noname', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='particularproblem',
            name='name',
            field=models.CharField(default='Noname', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='Noname', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='typicalproblem',
            name='name',
            field=models.CharField(default='Noname', max_length=255, verbose_name='Name'),
        ),
    ]
