# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0038_auto_20161111_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='baseperson',
            name='rating',
        ),
        migrations.AddField(
            model_name='privateperson',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
