# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0039_auto_20161113_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseperson',
            name='name',
            field=models.CharField(default='Noname', max_length=255, verbose_name='Name'),
        ),
    ]
