# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('edw', '0040_baseperson_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('datamart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edw.DataMart', verbose_name='DataMart')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Image')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'verbose_name': 'DataMart Image',
                'verbose_name_plural': 'DataMart Images',
            },
        ),
        migrations.AddField(
            model_name='datamart',
            name='images',
            field=models.ManyToManyField(through='edw.DataMartImage', to='filer.Image'),
        ),
    ]
