# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0041_auto_20161114_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseperson',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='particularproblem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='typicalproblem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
