# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0042_auto_20161118_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamartimage',
            old_name='datamart',
            new_name='data_mart',
        ),
    ]
