# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 14:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0044_auto_20161121_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamart',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Entities per page. Leave empty for default (by default: 40).', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='particularproblem',
            name='status',
            field=django_fsm.FSMField(default='draft', max_length=50, verbose_name='Status'),
        ),
    ]
