# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0045_auto_20161124_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_codes', models.TextField(blank=True, help_text="You enter on one index in line.\nUse '?' and '*' as universal substitutes.\n'?' replaces any symbol, '*' replaces any sequence of symbols (including I am empty).\nGaps are ignored. '_' replaces any quantity of gaps (but at least one).\nExample:\n2204*\n38?45\n23*\n123_4??", null=True, verbose_name='Postal codes')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edw.Term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Postal zone',
                'verbose_name_plural': 'Postal zones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='postalzone',
            unique_together=set([('term', 'active')]),
        ),
    ]
