# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0046_auto_20161124_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postalzone',
            options={'ordering': ('term__tree_id', 'term__lft'), 'verbose_name': 'Postal zone', 'verbose_name_plural': 'Postal zones'},
        ),
        migrations.AlterField(
            model_name='postalzone',
            name='postal_codes',
            field=models.TextField(blank=True, help_text="You enter on one index in line. Use '?' and '*' as universal substitutes. '?' replaces any symbol, '*' replaces any sequence of symbols (including I am empty). Gaps are ignored. '_' replaces any quantity of gaps (but at least one). Example: 2204*, 38?45, 23*, 123_4??.", null=True, verbose_name='Postal codes'),
        ),
    ]
