# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0047_auto_20161124_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamart',
            name='view_component',
            field=models.CharField(default='list', help_text='Default data mart entities view component.', max_length=50, verbose_name='View component'),
        ),
    ]
