# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0048_datamart_view_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamart',
            name='limit',
            field=models.IntegerField(blank=True, help_text='\u041e\u0431\u044a\u0435\u043a\u0442\u043e\u0432 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435. \u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c \u0434\u043b\u044f \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e (\u043f\u043e-\u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e: 40).', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limit'),
        ),
    ]
