# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0050_message_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particularproblem',
            name='messages',
        ),
        migrations.AddField(
            model_name='particularproblem',
            name='messages',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='edw.Message', verbose_name='Messages'),
        ),
    ]
