# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0051_auto_20161210_1758'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='particularproblemmessage',
            unique_together=set([('problem', 'message')]),
        ),
    ]
