# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0054_auto_20161210_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularproblemmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='edw.Message', verbose_name='Message'),
        ),
    ]
