# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0056_auto_20161210_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='particularproblemmessage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='particularproblemmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='particularproblemmessage',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='particularproblem',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='edw.ParticularProblem', verbose_name='Particular problem'),
        ),
        migrations.DeleteModel(
            name='ParticularProblemMessage',
        ),
    ]
