# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-11 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0057_auto_20161210_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='edw.ParticularProblem', to_field='id', verbose_name='Particular problem'),
        ),
        migrations.AlterField(
            model_name='particularproblem',
            name='status',
            field=django_fsm.FSMField(default='draft', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
