# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0059_auto_20161212_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='edw.ParticularProblem', verbose_name='Particular problem'),
        ),
    ]
