# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0062_auto_20161213_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
