# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0063_auto_20161213_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratePerson',
            fields=[
                ('baseperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.BasePerson')),
            ],
            options={
                'verbose_name': 'Moderate person',
                'verbose_name_plural': 'Moderate persons',
            },
            bases=('edw.baseperson',),
        ),
    ]
