# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-21 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0064_moderateperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='particularproblem',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solved at'),
        ),
    ]
