# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0066_auto_20170118_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mail_to',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Mail to'),
        ),
    ]
