# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import page_builder.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0067_auto_20170207_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.Entity')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sub_name', models.CharField(blank=True, max_length=600, null=True, verbose_name='sub name')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='author')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('builder_template', page_builder.fields.BuilderTemplateField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'News article',
                'verbose_name_plural': 'News articles',
            },
            bases=('edw.entity',),
        ),
    ]
