# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0068_newsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='entity_ptr',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
