# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0069_auto_20170316_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edw.Entity')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('lead', models.CharField(blank=True, max_length=600, null=True, verbose_name='Lead')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
            bases=('edw.entity',),
        ),
    ]
