# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import page_builder.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0070_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('builder_template', page_builder.fields.BuilderTemplateField(max_length=255, null=True, verbose_name='Template builder')),
            ],
            options={
                'verbose_name': 'Publication template',
                'verbose_name_plural': 'Publication templates',
            },
        ),
    ]
