# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0071_publicationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edw.PublicationTemplate', verbose_name='Template'),
            preserve_default=False,
        ),
    ]
