# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0072_publication_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='typicalproblem',
            name='deadline',
            field=models.PositiveIntegerField(default=30, help_text='The deadline for reply (In days).', verbose_name='Deadline'),
        ),
        migrations.AddField(
            model_name='typicalproblem',
            name='redline',
            field=models.PositiveIntegerField(default=25, help_text='The redline for reply (In days).', verbose_name='Redline'),
        ),
    ]
