# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0073_auto_20170421_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='typicalproblem',
            name='is_image_required',
            field=models.BooleanField(default=True, help_text='Is image required on a particular problem', verbose_name='Is problem image required'),
        ),
    ]
