# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_auth', '0002_auto_20160327_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, verbose_name='Domain name')),
            ],
            options={
                'db_table': 'auth_banned_email_domain',
                'verbose_name': 'Banned email domain',
                'verbose_name_plural': 'Banned email domains',
            },
        ),
    ]
