# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Entity Relation',
                'verbose_name_plural': 'Entity Relations',
            },
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_relations', to='todos.Todo', verbose_name='From Entity'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos.Term', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backward_relations', to='todos.Todo', verbose_name='To Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelation',
            unique_together=set([('from_entity', 'to_entity', 'term')]),
        ),
    ]
