# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('todos', '0003_auto_20160913_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Todo', verbose_name='Entity')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Image')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'verbose_name': 'Entity Image',
                'verbose_name_plural': 'Entity Images',
            },
        ),
    ]
