# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 13:11
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20160923_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamart',
            name='system_flags',
            field=bitfield.models.BitField([('delete_restriction', 'Delete restriction'), ('change_parent_restriction', 'Change parent restriction'), ('change_slug_restriction', 'Change slug restriction'), ('has_child_restriction', 'Has child restriction'), ('change_terms_restriction', 'Change terms restriction')], default=None, null=True, verbose_name='system flags'),
        ),
    ]
