# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20161006_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMartRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('b', 'Bidirectional'), ('f', 'Forward'), ('r', 'Reverse')], default='b', help_text='Defines the direction of relation on which selection is carried out', max_length=1, verbose_name='Relation direction')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Data mart relation',
                'verbose_name_plural': 'Data mart relations',
            },
        ),
        migrations.CreateModel(
            name='EntityRelatedDataMart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Related data mart',
                'verbose_name_plural': 'Entity related data marts',
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='_relations',
            field=models.ManyToManyField(through='todos.EntityRelation', to='todos.Todo'),
        ),
        migrations.AlterField(
            model_name='additionalentitycharacteristicormark',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos.Todo', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='additionalentitycharacteristicormark',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos.Term', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='datamart',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='_datamart_terms_+', to='todos.Term', verbose_name='Terms'),
        ),
        migrations.AddField(
            model_name='entityrelateddatamart',
            name='data_mart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos.DataMart', verbose_name='Data mart'),
        ),
        migrations.AddField(
            model_name='entityrelateddatamart',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos.Todo', verbose_name='Entity'),
        ),
        migrations.AddField(
            model_name='datamartrelation',
            name='data_mart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='todos.DataMart', verbose_name='Data mart'),
        ),
        migrations.AddField(
            model_name='datamartrelation',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='todos.Term', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='datamart',
            name='_relations',
            field=models.ManyToManyField(through='todos.DataMartRelation', to='todos.Term'),
        ),
        migrations.AddField(
            model_name='todo',
            name='related_data_marts',
            field=models.ManyToManyField(blank=True, related_name='_todo_related_data_marts_+', through='todos.EntityRelatedDataMart', to='todos.DataMart', verbose_name='Related data marts'),
        ),
        migrations.AlterUniqueTogether(
            name='datamartrelation',
            unique_together=set([('data_mart', 'term')]),
        ),
    ]
