# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20161017_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamart',
            name='ordering',
            field=models.CharField(default='-created_at', help_text='Default data mart entities ordering mode.', max_length=50, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='datamart',
            name='slug',
            field=models.SlugField(help_text='Used for URLs, auto-generated from name if blank.', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.SlugField(help_text='Used for URLs, auto-generated from name if blank.', verbose_name='Slug'),
        ),
    ]
