# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20161103_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamart',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Entities per page. Leave empty for default (by default: 12).', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limit'),
        ),
    ]
