# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0002_auto_20160727_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('order',), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='datamart',
            options={'verbose_name': 'Data mart', 'verbose_name_plural': 'Data marts'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
    ]
