# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, help_text='Is this object publicly visible.', verbose_name='Active')),
                ('object_name', models.CharField(max_length=255, verbose_name='Book Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_sample.book_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('object_name',),
            },
        ),
        migrations.CreateModel(
            name='BookTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(help_text='Description for the list view of books.', verbose_name='Description')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sample.Book')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booktranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
