# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edw', '0002_auto_20160727_1840'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True, help_text='Description for the list view of books.', null=True, verbose_name='Description')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='edw.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterUniqueTogether(
            name='booktranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
