# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20160629_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='object_name',
            new_name='name',
        ),
    ]
