# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20160629_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample.Book')),
                ('age', models.PositiveSmallIntegerField(choices=[(1, '0-6 month'), (2, '6-12 month'), (3, '1+ year')], verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Child book',
                'verbose_name_plural': 'Child books',
            },
            bases=('sample.book',),
        ),
    ]
