# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_booktranslation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktranslation',
            name='order',
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort by'),
            preserve_default=False,
        ),
    ]
