# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20160629_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Sort by'),
        ),
    ]
