# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20160629_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Sort by'),
        ),
    ]
