# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_auto_20160629_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample.Book')),
                ('ganre', models.PositiveSmallIntegerField(choices=[(1, 'Fantastic'), (2, 'Drama'), (3, 'Mistics')], verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Adult book',
                'verbose_name_plural': 'Adult books',
            },
            bases=('sample.book',),
        ),
    ]
