# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_adultbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultbook',
            old_name='ganre',
            new_name='genre',
        ),
    ]
