# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20160727_1840'),
        ('sample', '0012_auto_20160704_1533'),
    ]

    operations = [
    ]
