# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultbook',
            name='book_ptr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='childbook',
            name='book_ptr',
        ),
        migrations.DeleteModel(
            name='AdultBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='ChildBook',
        ),
    ]
