// Entities Actions
const NOTIFY_LOADING_ENTITIES = 'NOTIFY_LOADING_ENTITIES';
const NOTIFY_LOADING_ENTITY = 'NOTIFY_LOADING_ENTITY';
const LOAD_ENTITIES = 'LOAD_ENTITIES';
const LOAD_ENTITY = 'LOAD_ENTITY';
const SET_DATA_VIEW_COMPONENTS = 'SET_DATA_VIEW_COMPONENTS';
const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
const DO_NOTHING = 'DO_NOTHING';
const HIDE_VISIBLE_DETAIL = 'HIDE_VISIBLE_DETAIL';

export const actionTypes = {
  NOTIFY_LOADING_ENTITIES,
  NOTIFY_LOADING_ENTITY,
  LOAD_ENTITIES,
  LOAD_ENTITY,
  SET_DATA_VIEW_COMPONENTS,
  SET_CURRENT_VIEW,
  DO_NOTHING,
  HIDE_VISIBLE_DETAIL
};
