// Entities Actions
const NOTIFY_LOADING_ENTITIES = 'NOTIFY_LOADING_ENTITIES';
const LOAD_ENTITIES = 'LOAD_ENTITIES';
const SET_DATA_VIEW_COMPONENTS = 'SET_DATA_VIEW_COMPONENTS';
const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';

export const actionTypes = {
  NOTIFY_LOADING_ENTITIES,
  LOAD_ENTITIES,
  SET_DATA_VIEW_COMPONENTS,
  SET_CURRENT_VIEW
};
