// Tree Actions
const LOAD_TERMS_TREE = 'LOAD_TERMS_TREE';
const RELOAD_TERMS_TREE = 'RELOAD_TERMS_TREE';
const TOGGLE_TERM = 'TOGGLE_TERM';
const RESET_BRANCH = 'RESET_BRANCH';
const RESET_TERM = 'RESET_TERM';
const NOTIFY_LOADING_TERMS = 'NOTIFY_LOADING_TERMS';
const SET_PREV_TAGGED_ITEMS = 'SET_PREV_TAGGED_ITEMS';
export const actionTypes = {
  LOAD_TERMS_TREE,
  RELOAD_TERMS_TREE,
  TOGGLE_TERM,
  RESET_BRANCH,
  RESET_TERM,
  NOTIFY_LOADING_TERMS,
  SET_PREV_TAGGED_ITEMS
};

// Semantic Rules
const SEMANTIC_RULE_OR = 10;
const SEMANTIC_RULE_XOR = 20;
const SEMANTIC_RULE_AND = 30;
export const semanticRules = {
  SEMANTIC_RULE_OR,
  SEMANTIC_RULE_XOR,
  SEMANTIC_RULE_AND
};

// Structures
const STRUCTURE_TRUNK = "trunk";
const STRUCTURE_LIMB = "limb";
const STRUCTURE_BRANCH = "branch";
const STRUCTURE_NULL = null;
export const structures = {
  STRUCTURE_TRUNK,
  STRUCTURE_LIMB,
  STRUCTURE_BRANCH,
  STRUCTURE_NULL
};

// Specifications
const STANDARD_SPECIFICATION = 10;
const EXPANDED_SPECIFICATION = 20;
const REDUCED_SPECIFICATION = 30;
export const specifications = {
  STANDARD_SPECIFICATION,
  EXPANDED_SPECIFICATION,
  REDUCED_SPECIFICATION
};
