const SET_DATA_ENTITY = 'SET_DATA_ENTITY';
const ERROR_SET_DATA_ENTITY = 'ERROR_SET_DATA_ENTITY';
const CREATE_ENTITY = 'CREATE_ENTITY';
const ERROR_CREATE_ENTITY = 'ERROR_CREATE_ENTITY';
const GET_ENTITY = 'GET_ENTITY';
const ERROR_GET_ENTITY = 'ERROR_GET_ENTITY';
const DELETE_ENTITY = 'DELETE_ENTITY';
const ERROR_DELETE_ENTITY = 'ERROR_DELETE_ENTITY';
const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
const ERROR_UPLOAD_IMAGE = 'ERROR_UPLOAD_IMAGE';
const GET_ENTITY_IMAGES = 'GET_ENTITY_IMAGES';
const ERROR_GET_ENTITY_IMAGES = 'ERROR_GET_ENTITY_IMAGES';
const DELETE_IMAGE = 'DELETE_IMAGE';
const ERROR_DELETE_IMAGE = 'ERROR_DELETE_IMAGE';


export const actionTypes = {
  SET_DATA_ENTITY,
  ERROR_SET_DATA_ENTITY,
  CREATE_ENTITY,
  ERROR_CREATE_ENTITY,
  GET_ENTITY,
  ERROR_GET_ENTITY,
  DELETE_ENTITY,
  ERROR_DELETE_ENTITY,
  UPLOAD_IMAGE,
  ERROR_UPLOAD_IMAGE,
  GET_ENTITY_IMAGES,
  ERROR_GET_ENTITY_IMAGES,
  DELETE_IMAGE,
  ERROR_DELETE_IMAGE,
};
