// Web and native actions
export const NOTIFY_LOADING_ENTITIES = 'NOTIFY_LOADING_ENTITIES';
export const NOTIFY_LOADING_ENTITY = 'NOTIFY_LOADING_ENTITY';
export const LOAD_ENTITIES = 'LOAD_ENTITIES';
export const LOAD_ENTITY = 'LOAD_ENTITY';
export const SHOW_ENTITY_DESC = 'SHOW_ENTITY_DESC';
export const HIDE_ENTITY_DESC = 'HIDE_ENTITY_DESC';


// Native actions
export const DO_NOTHING = 'DO_NOTHING';
export const HIDE_VISIBLE_DETAIL = 'HIDE_VISIBLE_DETAIL';
