# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from update_terms import update_entities_terms
from update_relations import update_entities_relations
from update_images import update_entities_images
from update_related_data_marts import update_entities_related_data_marts
from update_additional_characteristics_or_marks import update_entities_additional_characteristics_or_marks
