import {
  getTerm,
  loadTree,
  reloadTree,
  readTree,
  notifyLoadingTerms,
  toggleTerm,
  toggleFilters,
  resetTerm,
  resetBranch,
  showInfo,
  hideInfo,
  setPrevTaggedItems,
} from './TermsTreeActions';

import {
  getEntity,
  getEntities,
  readEntities,
  notifyLoadingEntities,
  expandGroup,
  showDescription,
  hideDescription,
  toggleDropdown,
  selectDropdown,
  setDataViewComponents,
  setCurrentView,
  hideVisibleDetail,
} from './EntityActions';

import {
  changeActiveDataMart,
} from './DataMartListActions';

export default {
  getTerm,
  loadTree,
  reloadTree,
  readTree,
  notifyLoadingTerms,
  toggleTerm,
  toggleFilters,
  resetTerm,
  resetBranch,
  showInfo,
  hideInfo,
  getEntity,
  getEntities,
  readEntities,
  notifyLoadingEntities,
  expandGroup,
  showDescription,
  hideDescription,
  toggleDropdown,
  selectDropdown,
  changeActiveDataMart,
  setDataViewComponents,
  setCurrentView,
  hideVisibleDetail,
  setPrevTaggedItems,
};
